on:
  pull_request:

jobs:
  audivisor:
    name: 'Run audivisor'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: takumi-n/audivisor@gatest5
  audivisor:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
            ğŸŒ
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'audivisor[bot]'
